import FAQItem from "@/components/FAQItem";
import Link from "next/link";

const faqs = [
  { question: "How far is Star Nights from Nairobi?", answer: "We are located in Kwenia, Kilonito, Kajiado West, around 45 minutes from Nairobi depending on your starting point and traffic." },
  { question: "What is included with a stay?", answer: "Your stay includes the room, breakfast, and the quiet open-air setting that makes Star Nights special. Additional experiences can be arranged with our team." },
  { question: "Can I arrange a special experience?", answer: "Yes. Tell us about your occasion or interests when you get in touch and we will help shape a thoughtful visit." },
  { question: "Do you offer astro-tourism experiences?", answer: "Yes. Guests can spend the evening learning about the night sky, discovering constellations, and hearing the stories connected to them." },
  { question: "How do I reserve a room?", answer: "Choose a room from our booking page and send a reservation request. Our team will contact you to confirm availability before any payment is taken." },
];

export default function ContactPage() {
  return (
    <main className="bg-[#f5f1e9] text-[#24231f]">
      <section className="relative overflow-hidden bg-[#282820] px-6 py-20 text-white sm:px-10 lg:px-16 lg:py-24">
        <img src="/HeroImgTwo.jpg" alt="The landscape around Star Nights Magadi" className="absolute inset-0 h-full w-full object-cover opacity-40" />
        <div className="absolute inset-0 bg-gradient-to-r from-[#171812]/95 via-[#171812]/70 to-[#171812]/25" />
        <div className="relative mx-auto max-w-7xl"><Link href="/" className="font-inter text-sm text-white/70 transition hover:text-white">← Back to Star Nights</Link><p className="mt-12 font-inter text-sm font-semibold uppercase tracking-[0.24em] text-[#e7c889]">Come say hello</p><h1 className="mt-4 max-w-4xl font-raleway text-5xl leading-tight sm:text-7xl">Let’s plan something memorable.</h1><p className="mt-6 max-w-xl font-inter text-lg leading-8 text-white/70">Questions, special requests, and quiet getaway plans all have a place here.</p></div>
      </section>

      <section className="mx-auto grid max-w-7xl gap-8 px-6 py-16 sm:px-10 lg:grid-cols-[0.8fr_1.2fr] lg:px-16 lg:py-24">
        <aside className="bg-[#282820] p-7 text-white sm:p-9"><p className="font-inter text-sm font-semibold uppercase tracking-[0.2em] text-[#e7c889]">Get in touch</p><h2 className="mt-4 font-raleway text-4xl">We’re here to help.</h2><p className="mt-5 font-inter leading-7 text-white/70">Reach out before your stay, or send us a note while you are deciding what kind of night you need.</p><div className="mt-10 space-y-6 border-t border-white/20 pt-7 font-inter text-sm"><div><p className="text-white/50">Phone</p><a href="tel:+254769139060" className="mt-1 block transition hover:text-[#e7c889]">+254 769 13 90 60</a></div><div><p className="text-white/50">Email</p><a href="mailto:stay@star-nights-magadi.com" className="mt-1 block break-words transition hover:text-[#e7c889]">stay@star-nights-magadi.com</a></div><div><p className="text-white/50">Location</p><p className="mt-1">Kwenia, Kilonito<br />Kajiado West</p></div></div></aside>

        <div className="bg-white p-6 shadow-sm sm:p-9"><p className="font-inter text-sm font-semibold uppercase tracking-[0.2em] text-[#a36f35]">Send a message</p><h2 className="mt-3 font-raleway text-4xl">How can we help?</h2><form className="mt-8 flex flex-col gap-5"><div className="grid gap-5 sm:grid-cols-2"><div><label htmlFor="name" className="mb-2 block font-inter text-sm font-semibold">Full name</label><input id="name" name="name" type="text" required autoComplete="name" className="w-full rounded-md border border-[#d5ccbd] bg-[#fbf9f5] px-4 py-3 font-inter outline-none transition focus:border-[#a36f35] focus:ring-2 focus:ring-[#d7ad62]/40" /></div><div><label htmlFor="email" className="mb-2 block font-inter text-sm font-semibold">Email address</label><input id="email" name="email" type="email" required autoComplete="email" className="w-full rounded-md border border-[#d5ccbd] bg-[#fbf9f5] px-4 py-3 font-inter outline-none transition focus:border-[#a36f35] focus:ring-2 focus:ring-[#d7ad62]/40" /></div></div><div><label htmlFor="subject" className="mb-2 block font-inter text-sm font-semibold">What can we help with?</label><select id="subject" name="subject" defaultValue="general" className="w-full rounded-md border border-[#d5ccbd] bg-[#fbf9f5] px-4 py-3 font-inter outline-none transition focus:border-[#a36f35] focus:ring-2 focus:ring-[#d7ad62]/40"><option value="general">General question</option><option value="booking">Planning a booking</option><option value="special">Special request</option><option value="experience">Experiences and astro-tourism</option></select></div><div><label htmlFor="message" className="mb-2 block font-inter text-sm font-semibold">Message</label><textarea id="message" name="message" required rows={6} className="w-full resize-y rounded-md border border-[#d5ccbd] bg-[#fbf9f5] px-4 py-3 font-inter outline-none transition focus:border-[#a36f35] focus:ring-2 focus:ring-[#d7ad62]/40" /></div><button type="submit" className="inline-flex w-fit items-center rounded-md bg-[#282820] px-6 py-3 font-inter text-sm font-semibold text-white transition hover:bg-[#a36f35]">Send your message <span className="ml-3" aria-hidden="true">→</span></button><p className="font-inter text-xs text-[#77736b]">We’ll get back to you as soon as we can.</p></form></div>
      </section>

      <section className="border-t border-[#dcd4c6] bg-[#ebe5d9] px-6 py-16 sm:px-10 lg:px-16 lg:py-20"><div className="mx-auto max-w-3xl"><div className="mb-10"><p className="font-inter text-sm font-semibold uppercase tracking-[0.2em] text-[#a36f35]">Good to know</p><h2 className="mt-3 font-raleway text-4xl sm:text-5xl">Common questions.</h2></div><div>{faqs.map((faq) => <FAQItem key={faq.question} question={faq.question} answer={faq.answer} />)}</div></div></section>

      <section className="bg-[#d7ad62] px-6 py-14 sm:px-10 lg:px-16"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-6 sm:flex-row sm:items-center"><div><p className="font-inter text-sm font-semibold uppercase tracking-[0.2em] text-[#5a3a20]">Already feeling the pull?</p><h2 className="mt-2 font-raleway text-4xl text-[#211d16]">Find your room.</h2></div><Link href="/book" className="rounded-md bg-[#282820] px-6 py-3 font-inter text-sm font-semibold text-white transition hover:bg-black">Browse rooms →</Link></div></section>
    </main>
  );
}